_target_: torchvision.datasets.ImageFolder
n_channels: 3
root: "${filepaths.celeb_a_root}"
train:
  root: "${dataset.root}/train"
  _target_: "${dataset._target_}"
val:
  root: "${dataset.train.root}"
  _target_: "${dataset._target_}"
test:
  root: "${dataset.train.root}"
  _target_: "${dataset._target_}"
