# @package _global_
name: MISSING
version: "${submission_details.version}"
model:
  lm:
    _target_: core.lightning_module.BaseGAN
  noise_distn: "${noise_distn}"
  noise_dim: 100
train:
  batch_size: 128
  img_size: 64
  num_workers: 4
  channels_img: "${dataset.n_channels}"
  num_epochs: 99999
  features_disc: 64
  features_gen: 64
  ckpt_dir:
  criterion:
    _target_: torch.nn.BCELoss
optimisation:
  lr: MISSING
  disc_freq: 1
  gen_freq: 1
  lr_scheduler: "${lr_scheduler}"
loss_weight: MISSING
optimiser: MISSING
val:
  use_fid: True
  inception_stats_filepath: "${dataset.root}/val_inception_stats.pkl"
  fid_n_samples: 5000
discriminator: MISSING
generator: MISSING
debug:
  verbose_shape: false
  fast_dev_run: false
figure_details:
    dir: "figures"
    filename: ""
hydra:
  output_subdir: null
  run:
    dir: .
  job_logging:
    disable_existing_loggers: false
defaults:
 - dataset: MISSING
 - filepaths: local
 - submission_details: local
 - noise_distn: normal
 - lr_scheduler: step_lr
 - override hydra/job_logging: disabled
