# @package _global_
name: MISSING
version:
num_gpus: 1
model:
  lm:
    _target_: core.lightning_module.BaseGAN
  noise_distn: "${noise_distn}"
  noise_dim: 100
train:
  batch_size: 128
  img_size: 64
  num_workers: 4
  channels_img: "${dataset.n_channels}"
  num_epochs: 99999
  features_disc: 64
  features_gen: 64
  ckpt_dir:
  criterion:
    _target_: torch.nn.BCEWithLogitsLoss
  data_mean: 0.5
  data_std: 0.5
optimisation:
  lr: MISSING
  disc_freq: 1
  gen_freq: 1
  lr_scheduler: "${lr_scheduler}"
loss_weight: MISSING
optimiser: MISSING
disc_optimiser: "${optimiser}"
gen_optimiser: "${optimiser}"
val:
  use_fid: True
  inception_stats_filepath: "${dataset.root}/val_inception_stats.pkl"
  fid_n_samples: 5000
discriminator:
  img_size: "${train.img_size}"
  final_sigmoid: false
generator:
  img_size: "${train.img_size}"
debug:
  verbose_shape: false
  fast_dev_run: false
figure_details:
    dir: "figures"
    filename: ""
    fid_callback: True
    save_all: False
precision: 16
save_ckpts: True
calc_fid: True
use_resolution_annealing: False
hydra:
  output_subdir: null
  run:
    dir: .
  job_logging:
    disable_existing_loggers: false
defaults:
 - dataset: celeb_a
 - filepaths: local
 - noise_distn: normal
 - lr_scheduler: step_lr
 - override hydra/job_logging: disabled
