# @package _global_
name: MISSING
train:
  lr: 2e-4
  beta1: 0.5
  beta2: 0.999
  betas: ["${train.beta1}", "${train.beta2}"]
  batch_size: 128
  img_size: 64
  num_workers: 4
  channels_img: "${dataset.n_channels}"
  noise_dim: 100
  num_epochs: 99
  features_disc: 64
  features_gen: 64
  ckpt_dir:
val:
  use_fid: True
  inception_stats_filepath: "${dataset.root}/val_inception_stats.pkl"
discriminator:
  _target_: core.networks.Discriminator
  channels_img: "${train.channels_img}"
  features_d: "${train.features_disc}"
generator:
  _target_: core.networks.Generator
  channels_noise: "${train.noise_dim}"
  channels_img: "${train.channels_img}"
  features_g: "${train.features_gen}"
debug:
  verbose_shape: false
  fast_dev_run: false
figure_details:
    dir: "figures"
    filename: ""
hydra:
  output_subdir: null
  run:
    dir: .
  job_logging:
    disable_existing_loggers: false
defaults:
 - dataset: MISSING
 - filepaths: local
 - override hydra/job_logging: disabled
