name:
    dc_gan
train:
  lr: 2e-4
  beta1: 0.5
  beta2: 0.999
  batch_size: 128
  img_size: 64
  num_workers: 4
  channels_img: 1
  noise_dim: 100
  num_epochs: 99
  features_disc: 64
  features_gen: 64
discriminator:
  _target_: core.networks.Discriminator
  channels_img: "${train.channels_img}"
  features_d: "${train.features_disc}"
generator:
  _target_: core.networks.Generator
  channels_noise: "${train.noise_dim}"
  channels_img: "${train.channels_img}"
  features_g: "${train.features_gen}"
debug:
  verbose_shape: false
hydra:
  output_subdir: null
  run:
    dir: .
  job_logging:
    disable_existing_loggers: false
defaults:
 - hydra/job_logging: disabled
 - dataset: MISSING
