# @package _global_
name: dc_gan
train:
  img_size: 64
  training_step:
    _target_: core.training_steps.dc
optimisation:
  lr: 2e-4
  beta1: 0.5
  beta2: 0.999
optimiser:
  _target_: torch.optim.Adam
  lr: "${optimisation.lr}"
  betas: ["${optimisation.beta1}", "${optimisation.beta2}"]
discriminator:
  _target_: core.networks.Discriminator
  channels_img: "${train.channels_img}"
  features_d: "${train.features_disc}"
generator:
  _target_: core.networks.Generator
  channels_noise: "${train.noise_dim}"
  channels_img: "${train.channels_img}"
  features_g: "${train.features_gen}"
defaults:
  - /figures@figures.sample_grid: sample_grid
  - /figures@figures.interpolation: interpolation
  - override /dataset: mnist
