# @package _global_
name: hologan
model:
  noise_distn: "${noise_distn}"
  lm:
    _target_: core.lightning_module.HOLOGAN
  noise_dim: 128
train:
  batch_size: 32
  img_size: 64
  num_epochs: 25
  criterion:
    _target_: torch.nn.BCEWithLogitsLoss
optimisation:
  lr: 1e-4
  disc_freq: 1
  gen_freq: 2
  beta1: 0.9
  beta2: 0.999
optimiser:
  _target_: torch.optim.Adam
  lr: "${optimisation.lr}"
  betas: ["${optimisation.beta1}", "${optimisation.beta2}"]
discriminator:
  _target_: core.models.hologan_discriminator.Discriminator
  in_planes: "${train.channels_img}"
  out_planes: 64
  z_planes: "${model.noise_dim}"
generator:
  _target_: core.models.hologan_generator.Generator
  in_planes: 64
  out_planes: "${train.channels_img}"
  z_planes: "${model.noise_dim}"
  gpu: True
  img_size: "${train.img_size}"
  view_args:
    elevation_low: 70
    elevation_high: 110
    azimuth_low: 220
    azimuth_high: 320
    scale_low: 1
    scale_high: 1
    transX_low: 0
    transX_high: 0
    transY_low: 0
    transY_high: 0
    transZ_low: 0
    transZ_high: 0
    batch_size: "${train.batch_size}"
defaults:
  - /figures@figures.sample_grid: sample_grid
  - /figures@figures.interpolation: interpolation
  - /figures@figures.azimuth_step: azimuth_step
  - /figures@figures.elevation_step: elevation_step
  - override /noise_distn: uniform
  - override /lr_scheduler: hologan
  - override /dataset: mnist
