# @package _global_
name: pigan
model:
  noise_distn: "${noise_distn}"
  lm:
    _target_: core.lightning_module.PIGAN
  noise_dim: 512
train:
  batch_size: 12
  training_resolution: 16
  criterion:
    _target_: torch.nn.BCEWithLogitsLoss
optimisation:
  beta1: 0
  beta2: 0.9
loss_weight:
  reg: 10
disc_optimiser:
  _target_: torch.optim.Adam
  lr: 4e-4
  betas: ["${optimisation.beta1}", "${optimisation.beta2}"]
gen_optimiser:
  _target_: torch.optim.Adam
  lr: 5e-5
  betas: ["${optimisation.beta1}", "${optimisation.beta2}"]
discriminator:
  _target_: core.models.pigan.Discriminator
  img_size: "${train.img_size}"
  init_chan: "${train.features_disc}"
  init_resolution: "${train.training_resolution}"
generator:
  _target_: core.models.pigan.Generator
  channels_noise: "${model.noise_dim}"
  channels_img: "${train.channels_img}"
  features_g: "${train.features_gen}"
  nerf_cfg: "${nerf}"
  view_args:
    azimuth_low: 220
    azimuth_high: 320
    elevation_low: 0
    elevation_high: 0
    camera_dist: 0.1
nerf:
  n_pts_per_ray: 32
  n_pts_per_ray_fine: 32
  min_depth: 0.1
  max_depth: 1.0
  stratified: True
  stratified_test: False
  chunk_size: 6000
  density_noise_std: 0.0
  latent_z_dim: "${model.noise_dim}"
  siren_dim_hidden: 256
  siren_num_layers: 6
save_ckpts: False
calc_fid: False
use_resolution_annealing: True
resolution_annealing:
    update_epochs: [1,2]
    resolutions: [16,32,64]
variable_batch_size:
    update_epochs: "${resolution_annealing.update_epochs}"
    batch_sizes: [64,16,4]
    # batch_sizes: [4,4,4] #DEVEL version
figure_details:
  fid_callback: False
  save_all: True
defaults:
  - /figures@figures.sample_grid: sample_grid_small
  - /figures@figures.azimuth_gif: azimuth_gif_small
