# @package _global_
name: pigan
model:
  noise_distn: "${noise_distn}"
  lm:
    _target_: core.lightning_module.PIGAN
  noise_dim: 128
train:
  batch_size: 12
  training_resolution: 16
  num_epochs: 25
  criterion:
    _target_: torch.nn.BCEWithLogitsLoss
optimisation:
  lr: 1e-4
  beta1: 0.5
  beta2: 0.999
optimiser:
  _target_: torch.optim.Adam
  lr: "${optimisation.lr}"
  betas: ["${optimisation.beta1}", "${optimisation.beta2}"]
discriminator:
  _target_: core.models.pigan.Discriminator
  img_size: "${train.img_size}"
  init_chan: "${train.features_disc}"
  init_resolution: "${train.training_resolution}"
generator:
  _target_: core.models.pigan.Generator
  channels_noise: "${model.noise_dim}"
  channels_img: "${train.channels_img}"
  features_g: "${train.features_gen}"
  nerf_cfg: "${nerf}"
  azimuth_low: 220
  azimuth_high: 320
nerf:
  n_pts_per_ray: 16
  n_pts_per_ray_fine: 16
save_ckpts: False
calc_fid: False
figure_details:
  fid_callback: False
defaults:
  - /figures@figures.sample_grid: sample_grid
  - override /dataset: mnist
