# @package _global_
name: wgan
train:
  img_size: 64
  batch_size: 64 
  weight_clip: 1e-2
  training_step:
    _target_: core.training_steps.wgan
discriminator:
  _target_: core.networks.Discriminator
  channels_img: "${train.channels_img}"
  features_d: "${train.features_disc}"
  final_sigmoid: false
generator:
  _target_: core.networks.Generator
  channels_noise: "${train.noise_dim}"
  channels_img: "${train.channels_img}"
  features_g: "${train.features_gen}"
optimisation:
  lr: 5e-5
  disc_freq: 5
  gen_freq: 1
disc_optimiser:
  _target_: torch.optim.RMSprop
  lr: "${optimisation.lr}"
gen_optimiser:
  _target_: torch.optim.RMSprop
  lr: "${optimisation.lr}"

defaults:
  - /figures@figures.sample_grid: sample_grid
  - /figures@figures.interpolation: interpolation
  - override /dataset: mnist
