# @package _global_
name: wgan_gp
train:
  img_size: 64
  batch_size: 64 
  training_step:
    _target_: core.training_steps.wgan_gp
discriminator:
  _target_: core.networks.Discriminator
  channels_img: "${train.channels_img}"
  features_d: "${train.features_disc}"
  norm: instance_norm2d
  final_sigmoid: false
generator:
  _target_: core.networks.Generator
  channels_noise: "${train.noise_dim}"
  channels_img: "${train.channels_img}"
  features_g: "${train.features_gen}"
optimisation:
  lr: 1e-4
  beta1: 0
  beta2: 0.9
loss_weight:
  lambda_gp: 10
disc_optimiser:
  _target_: torch.optim.Adam
  lr: "${optimisation.lr}"
  betas: ["${optimisation.beta1}", "${optimisation.beta2}"]
gen_optimiser:
  _target_: torch.optim.Adam
  lr: "${optimisation.lr}"
  betas: ["${optimisation.beta1}", "${optimisation.beta2}"]

defaults:
  - /figures@figures.sample_grid: sample_grid
  - /figures@figures.interpolation: interpolation
  - override /dataset: mnist
