data:
  type: lsun
  train_dir: data/LSUN
  test_dir: data/LSUN
  lsun_categories_train: [tower_train]
  lsun_categories_test: [tower_test]
  img_size: 256
generator:
  name: resnet3
  kwargs:
    nfilter: 64
    embed_size: 1
discriminator:
  name: resnet3
  kwargs:
    nfilter: 64
    embed_size: 1
z_dist:
  type: gauss
  dim: 256
training:
  out_dir: output/pretrained/lsun_tower
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/gan_stability/models/lsun_tower-1af5e570.pt
  batch_size: 32
  sample_size: 64 
  sample_nrow: 8
interpolations:
  nzs: 10
  nsubsteps: 75
